# Generated by Django 4.2.1 on 2023-06-28 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='cources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(upload_to='static/images')),
                ('img2', models.ImageField(upload_to='static/images')),
                ('img3', models.ImageField(upload_to='static/images')),
                ('img4', models.ImageField(upload_to='static/images')),
                ('img5', models.ImageField(upload_to='static/images')),
                ('name', models.CharField(max_length=100)),
                ('Descriptiontital', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('Status', models.CharField(max_length=100)),
                ('teacher', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.category')),
            ],
        ),
    ]
