# Generated by Django 4.2.1 on 2023-06-29 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='postcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='static/images')),
                ('post_name', models.CharField(max_length=100)),
                ('post_tital', models.CharField(max_length=100)),
                ('post', models.TextField()),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('written_by', models.CharField(max_length=50)),
                ('great_name', models.CharField(max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.postcategory')),
            ],
        ),
    ]
