# Generated by Django 4.2.1 on 2023-06-30 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_cources_img1_alter_cources_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cources',
            name='img1',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cources',
            name='img2',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cources',
            name='img3',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cources',
            name='img4',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='cources',
            name='img5',
            field=models.ImageField(upload_to='media'),
        ),
    ]
