# Generated by Django 4.2.1 on 2023-07-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_home_interface_price_plans_recommendations'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='contact_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Countery', models.CharField(max_length=50)),
                ('City', models.CharField(max_length=50)),
                ('Streat', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=50)),
                ('Facebook', models.CharField(max_length=50)),
                ('Telegram', models.CharField(max_length=50)),
                ('spurt_sevice', models.CharField(max_length=50)),
                ('ofice', models.CharField(max_length=50)),
                ('personal', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='recommendations',
            name='name_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
