# Generated by Django 4.2.1 on 2023-07-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_contact_data_contact_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='my_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('magac', models.CharField(max_length=100)),
                ('iimel', models.EmailField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('fikrad', models.TextField()),
            ],
        ),
    ]
