# Generated by Django 4.2.1 on 2023-07-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_my_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='educational_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tital', models.CharField(max_length=100)),
                ('date', models.EmailField(max_length=100)),
                ('sub_tital', models.CharField(max_length=100)),
                ('information', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='work_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tital', models.CharField(max_length=100)),
                ('date', models.EmailField(max_length=100)),
                ('sub_tital', models.CharField(max_length=100)),
                ('information', models.TextField()),
            ],
        ),
    ]
